### ISSUE TITLE
is there working on seagate drive 

### ISSUE THREAD

**Issue by MaminHakim** [westerndigitalcorporation/libzbc#45]
Hi, I'm looking to make partitions on my SMR host managed seagate disk. is this working on my drive ?

**Comment by damien-lemoal** [comment]
GPT partitions are not supported in Linux with SMR host managed drives, irrespective of the device vendor. If you need a "smaller" chunk of the drive to be exposed as a block device, use dm-linear. See: https://zonedstorage.io/linux/part/ and https://zonedstorage.io/linux/dm/#dm-linear.
