### ISSUE TITLE
License Question (BSD and/or LGPL)

### ISSUE THREAD

**Issue by jrobhoward** [westerndigitalcorporation/libzbc#46]
This is more of a question than a problem/issue..

**Background:**
I am interested in writing Rust bindings for libzbc.  I see the header and library source files of libzbc have both `BSD-2-Clause` and `LGPL-3.0-or-later` licenses present.  If/when I finish this poject, I'd like to release it under the same licenses as libzbc.

**Question:**
Are consumers of libzbc free to choose from either license, or will they need to comply with both?
Said another way: Will anybody linking statically to libzbc also need to release their application's source code in order to comply with LGPL obligations (since there is no static linking exception)?

I can organize the Rust project to link against libzbc either way (statically, or dynamically).  I'll probably add a feature flag so linking either way remains possible.  I'm just trying to decide which method of linking should be the default.

Thanks in advance for any guidance / much appreciated

**Comment by damien-lemoal** [comment]
With Dual licensing, the user is free to choose a license for the derivative software (or the software that uses the library), as long as said license is compatible with at least one of the license of libzbc. E.g., if your code only uses libzbc API with dynamic linking, then your software can use any license compatible with either BSD-2 clause *or* LGPL-v3. If on the other hand your code copies or modify part of libzbc code, then your software licensing must follow the restrictions of either of libzbc license, namely copyright notice for BSD and keep the source open for LGPL.

What is the usual license used for Rust crates/bindings ?

**Comment by dmitry-fomichev** [comment]
In my experience, the vast majority of public Rust crates use _Apache-2.0 OR MIT_ dual licensing. The second largest subset just bears _MIT_ license. _BSD-3-Clause_ and _MIT OR Unlicense_ also seem to be popular options. I wonder why BSD-2-Clause is less popular...  it is less restrictive than the 3-clause variant and, in my understanding, it is compatible with LGPL.

**Comment by MatiasBjorling** [comment]
If you haven't already considered it, I would be thrilled if the bindings
would be made for libzbd, which also includes support for zns ssds.

Libzbd is libzbc without the ata/scsi pass-through logic.

**Comment by jrobhoward** [comment]
> What is the usual license used for Rust crates/bindings ?
..
> In my experience, the vast majority of public Rust crates use Apache-2.0 OR MIT dual licensing..
..
> I wonder why BSD-2-Clause is less popular...

As Dmitry mentioned above, MIT and Apache are the most common licenses in the Rust community. Rust's build system pulls in its dependencies as source code and (usually / by default) links statically when producing the final binary.

I can speculate:

- Rust's build system and static linking contribute to the permissive licenses being more prevalent than GPL and LGPL.
- I don't know why BSD-2-Clause is less popular in the Rust community (vs MIT/Apache).  My best guess is it's just "intertia": Folks see MIT or Apache licenses being used in other projects and continue using it because it's close enough to meet their needs.


> If you haven't already considered it, I would be thrilled if the bindings
would be made for libzbd..

- Sure.  I mothballed my local libzbc branch and started work on libzbd bindings instead.
- Since libzbd is LGPL-only, my original question about dual licensing no longer applies.
- Users of `libzbd` Rust bindings would need to already have `/usr/lib/libzbd.so` built & present as a prerequisite (in that location, or somewhere accessible via LD_LIBRARY_PATH).  A git submodule will checkout libzbd project's source code and Rust's build system will make use of its `include/libzbd/zbd.h` header file to help generate the Rust bindings.
- Linking to `libzbd.so` will be dynamic, and consumers of the Rust bindings should be free to use their own licenses (e.g. MIT|Apache).
- Users of the Rust bindings are free to substitute in their own modified version of `libzbd` (by changing the git submodule location and/or swapping in an alternate `/usr/lib/libzbd.so` binary).

Thanks for the feedback.
