### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [westerndigitalcorporation/libzbc#48]
I would like to point out that identifiers like “[`_LIBZBC_H_`](https://github.com/westerndigitalcorporation/libzbc/blob/d42f82804dd3436a979b754108cf5234475fb5ec/include/libzbc/zbc.h#L14 "Update candidate")” and “[`__GZBC_H__`](https://github.com/westerndigitalcorporation/libzbc/blob/d42f82804dd3436a979b754108cf5234475fb5ec/tools/gui/gzbc.h#L11 "Another update candidate")” [do not fit](https://wiki.sei.cmu.edu/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by damien-lemoal** [comment]
Will fix that.
