### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [westerndigitalcorporation/libzbc#49]
Would you like to add more error handling for return values from functions like the following?
- [fprintf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output") ⇒ [zbc_print_device_info](https://github.com/westerndigitalcorporation/libzbc/blob/0826923e4c486ab6ab3435f20b71f7a5d8f3598d/lib/zbc.c#L402)
- [strdup](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [zbc_block_handle_partition](https://github.com/westerndigitalcorporation/libzbc/blob/0826923e4c486ab6ab3435f20b71f7a5d8f3598d/lib/zbc_block.c#L202)

**Comment by damien-lemoal** [comment]
Patches are welcome.
